spring.application.name=expense-tracker

# Connect with Postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api.key=AIzaSyDifMJ1bebUoO-_CePj2uJ66VVgAnCh9Jw